### ISSUE TITLE
Building Dospad

### ISSUE THREAD

**Issue by convolutionbbs** [litchie/dospad#41] opened 2016-06-25 00:07 UTC
Hello,
Dospad 2 on the App Store has been broke for a long time- no iTunes file sharing or iPad Pro external keyboard support.  

If one were so inclined to obtain a developer account, would this code be compatible with swift / Xcode on a MAC to be deployed as a testing app?  I'd like to be able to access the dos file system (install programs) and use the Smart Keyboard on an iPad Pro.

I haven't built any code for iOS and was wondering if this would work for my device.

Thanks!

**Comment by NE1WeKnow** [comment] 2016-06-25 06:03
Hi 

I have done this just recently having never built any code before about 3 months ago when I built GBA4IOS.  It's completely free to be a private developer and all the tools are free. 

Not sure about the Smart Keyboard support but you can access the file system after using file sharing to load files. 

Only thing I will add is the dospad beta app suddenly stopped opening today on my iphone after having used it several times the past couple of weeks. It's also not listed as a developer app under Device Management but not sure if it was there to begin with.

**Comment by EriolGaurhoth** [comment] 2016-06-27 20:29
I can confirm that the build made from the latest version on here does not have smart keyboard support, and I opened an issue for it about 2 weeks ago:

https://github.com/litchie/dospad/issues/40

**Comment by convolutionbbs** [comment] 2016-07-02 12:18
Thanks for the assistance.  I'm glad I asked before getting a Mac, struggling to compile, and wondering why my smart keyboard doesn't work.  Does anyone know how hard it would be to get this added?

**Comment by jabz10** [comment] 2016-08-29 12:05
so when I build this and install on iPad pro, I still get the batch file running, I can't pick any game in the file.  How do I drop to C:\ prompt?    Also when looking in iTunes there is no Sharing folder, so how do I actually add games to this version that I can build/sign.

**Comment by landswipe** [comment] 2016-09-04 13:56
Smart keyboard support should be fine now once #43 is merged, but only the modifiers (ALT/SHIFT/etc) were broken for me. @convolutionbbs was it not working for you are all?

**Comment by landswipe** [comment] 2016-09-04 13:58
Another point to mention, if you want to use iFunBox or similar to load files into iDOS2 (while side loading), you might have to set UIFileSharingEnabled to "true" in the iDOS-info.plist file (I had to).

**Comment by ecstaticax** [comment] 2016-09-18 18:56
I cannot compile "No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=x86_64, VALID_ARCHS=i386)." what can I do to solve the problem?

**Comment by billdwhite** [comment] 2016-09-23 00:51
Same problem here (No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=x86_64, VALID_ARCHS=i386).)
I'm trying to build for iOS10 on my iPhone 7

**Comment by ecstaticax** [comment] 2016-09-23 09:29
I solved. You can find the solution here.
http://stackoverflow.com/questions/22328882/xcode-5-1-no-architectures-to-compile-for-only-active-arch-yes-active-arch-x

Btw now keyboard doesn't work :-(

**Comment by landswipe** [comment] 2016-09-26 10:58
Are you finding event he built-in (software) keyboard not working?

**Comment by ecstaticax** [comment] 2016-09-26 11:01
At the end, after I killed the compiled app and ran it again, everything worked, even with iPad Pro Smart Keyboard.

**Comment by landswipe** [comment] 2016-09-26 11:10
Weird I found the keyboard is not working at all for me on iPhone 7, but fine on iPad pro (10.0.2).

**Comment by landswipe** [comment] 2016-09-26 11:29
Actually it's working fine. The default PLAY.BAT threw me off, 1/2/3/4 keys do nothing with a fresh build from github ;)

**Comment by landswipe** [comment] 2016-09-26 13:35
Just submitted #44 to add some handy mappings for the SmartKeyboard. Let me know if you find them useful (or have suggestions on how to do it differently).

**Comment by ecstaticax** [comment] 2016-09-26 14:11
They would be great, because there are not function keys or escape on smart keyboard...

**Comment by litchie** [comment] 2016-09-27 01:31
@landswipe Thank you for the fixes.

**Closed** 2020-10-21 15:58 UTC
